ワクチンに関するグラフを追加
Murayu0225/covid19-chocolate pull request #455
Opened 2021-07-02 10:34 UTC by Murayu0225

#453

2021-07-02 14:34 UTC, sagami-stopcovid19-dev requested changes
文末表記の変更をお願いします。

2021-07-02 14:34 UTC, sagami-stopcovid19-dev commented on components/index/CardsReference/VaccineInfo65/Card.vue
> +                  'ワクチン接種記録システム（VRS）のデータを基に、接種券の発行市町村別に集計しています。'
文末を変更
```suggestion
                  'ワクチン接種記録システム（VRS）のデータを基に、接種券の発行市町村別に集計している'
```

2021-07-02 14:34 UTC, sagami-stopcovid19-dev commented on components/index/CardsReference/VaccineInfo65/Card.vue
> +                  '総務省が公表している「住民基本台帳に基づく人口、人口動態及び世帯数」内の「【統計】令和2年住民基本台帳年齢階級別人口」を基に高齢者の全人口を分母にし、接種率を出しています。'
文末を変更
```suggestion
                  '総務省が公表している「住民基本台帳に基づく人口、人口動態及び世帯数」内の「【統計】令和2年住民基本台帳年齢階級別人口」を基に高齢者の全人口を分母にし、接種率を出している'
```

2021-07-03 05:28 UTC, Murayu0225 commented
> 文末表記の変更をお願いします。

対応します

2021-07-03 05:32 UTC, sagami-stopcovid19-dev approved these changes
LGTM!

2021-07-03 06:49 UTC, sagami-stopcovid19-dev requested changes
件数でした！

2021-07-03 10:48 UTC, sagami-stopcovid19-dev approved these changes
LGTM!!
件数表記になっていることを確認済み。

2021-07-03 10:54 UTC, merged