P-1002
Murayu0225/covid19-chocolate pull request #496
Opened 2021-07-15 07:04 UTC by Murayu0225

2021-07-15 07:05 UTC, Murayu0225 commented
<!--
  0 failure: 
  1 warning:  `libraries/auto_g...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  `libraries/auto_generated/data_converter/convertVaccination.ts` が変更されています。追加したコメントなどが削除されないよう注意してください。
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 591606aa98e7ddaa788d7908d6cf08aedf50b6d3
</p>

2021-07-18 07:36 UTC, Murayu0225 commented
v1.00.150にて追加機能にする予定
データに関して県と市に問い合わせを行ってます。

- データ類

- [ ] 県
- [ ] 市

- コード関連

- [×] 外枠
- [×] グラフ
- [×] パスを通す
- [ ] データ入力

---------

TrackingID : P-1002-C1
DO NOT DELETE THIS COMMENT

2021-07-20 12:07 UTC, sagami-stopcovid19-dev approved these changes
検証用

2021-07-20 12:08 UTC, sagami-stopcovid19-dev requested changes
Auto systemが動作していない

2021-07-20 12:12 UTC, sagami-stopcovid19-dev approved these changes
検証用

2021-07-20 12:14 UTC, sagami-stopcovid19-dev requested changes
検証完了

2021-07-20 22:10 UTC, Murayu0225 commented
Debugging now.
We'll launch this update on 21th Jul.

2021-07-20 22:23 UTC, sagami-stopcovid19-dev approved these changes

2021-07-21 03:06 UTC, merged